dist: trusty

install:
- source scripts/travis-install-cmake.sh
- export CC=/usr/bin/gcc-7
- export CXX=/usr/bin/g++-7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - g++-7
    - libjack-jackd2-dev
    - libgles2-mesa-dev
    # For GLFW
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev

cache:
  directories:
    - external
    - cmake

script:
- $CMAKE . -DCMAKE_BUILD_TYPE=Release
- make all
- bin/test

# For pushing documentation
env:
  global:
  - ENCRYPTION_LABEL: "388c738922bf"
  - COMMIT_AUTHOR_EMAIL: "topisani@hamsterpoison.com"

notifications:
  email: false
